// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniHackthonSEF.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniHackthonSEF.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904050210_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiniHackthonSEF.Api.Models.ItemReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Type", "IsResolved");

                    b.ToTable("ItemReports", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactInfo = "nimal@campus.lk",
                            CreatedAt = new DateTime(2026, 9, 3, 8, 30, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 9, 2),
                            Description = "Small black wallet with a university ID and bank cards inside.",
                            IsResolved = false,
                            Location = "Main Library, Ground Floor",
                            Name = "Black leather wallet",
                            Type = "Lost",
                            UpdatedAt = new DateTime(2026, 9, 3, 8, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ContactInfo = "077 456 9821",
                            CreatedAt = new DateTime(2026, 9, 3, 12, 15, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 9, 3),
                            Description = "Metal water bottle with a white mountain sticker on the side.",
                            IsResolved = false,
                            Location = "Faculty of Computing Lab 2",
                            Name = "Blue water bottle",
                            Type = "Found",
                            UpdatedAt = new DateTime(2026, 9, 3, 12, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ContactInfo = "security@campus.lk",
                            CreatedAt = new DateTime(2026, 9, 2, 7, 40, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 9, 1),
                            Description = "Student ID belonging to K. Perera, found near the cafeteria entrance.",
                            IsResolved = true,
                            Location = "University Cafeteria",
                            Name = "Student ID card",
                            Type = "Found",
                            UpdatedAt = new DateTime(2026, 9, 2, 7, 40, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            ContactInfo = "071 234 8810",
                            CreatedAt = new DateTime(2026, 8, 31, 10, 10, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 8, 30),
                            Description = "Grey Casio fx-991ES calculator in a transparent cover.",
                            IsResolved = false,
                            Location = "Engineering Lecture Hall B",
                            Name = "Casio scientific calculator",
                            Type = "Lost",
                            UpdatedAt = new DateTime(2026, 8, 31, 10, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            ContactInfo = "student.affairs@campus.lk",
                            CreatedAt = new DateTime(2026, 8, 30, 6, 15, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 8, 29),
                            Description = "Compact red umbrella found after the afternoon lecture.",
                            IsResolved = false,
                            Location = "Arts Building, Room 204",
                            Name = "Red umbrella",
                            Type = "Found",
                            UpdatedAt = new DateTime(2026, 8, 30, 6, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            ContactInfo = "076 555 1274",
                            CreatedAt = new DateTime(2026, 8, 29, 13, 25, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 8, 28),
                            Description = "Black 32GB USB drive with a small green keyring.",
                            IsResolved = true,
                            Location = "IT Centre",
                            Name = "USB flash drive",
                            Type = "Lost",
                            UpdatedAt = new DateTime(2026, 8, 29, 13, 25, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
