import { useEffect, useState } from 'react'
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, Mail, MapPin, PackageOpen, Pencil, Trash2 } from 'lucide-react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import Loading from '../components/Loading'
import { deleteItem, getItem, resolveItem } from '../services/itemService'
import { formatDate } from '../utils/format'

export default function ItemDetails() {
  const {id}=useParams(); const location=useLocation(); const navigate=useNavigate()
  const [item,setItem]=useState(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(location.state?.message||''); const [error,setError]=useState('')
  useEffect(()=>{getItem(id).then(setItem).catch((e)=>setError(e.message)).finally(()=>setLoading(false))},[id])
  const resolve=async()=>{setBusy(true);try{setItem(await resolveItem(id));setMessage('Great news — this report is now resolved.')}catch{setError('The report could not be resolved. Please try again.')}finally{setBusy(false)}}
  const remove=async()=>{if(!window.confirm('Delete this report permanently? This action cannot be undone.'))return;setBusy(true);try{await deleteItem(id);navigate('/items')}catch{setError('The report could not be deleted. Please try again.');setBusy(false)}}
  if(loading)return <section className="detail-page"><div className="container"><Loading label="Loading report…"/></div></section>
  if(error&&!item)return <section className="detail-page"><div className="container"><div className="empty-state"><PackageOpen size={44}/><h3>Report unavailable</h3><p>{error}</p><Link to="/items" className="btn btn-secondary">Browse reports</Link></div></div></section>
  return <section className="detail-page"><div className="container"><Link to="/items" className="text-link back-link"><ArrowLeft size={16}/> Back to reports</Link>{message&&<div className="status-message">{message}</div>}{error&&<div className="status-message error-message">{error}</div>}<div className="detail-layout"><article className="detail-card"><div className={`detail-visual ${item.type.toLowerCase()}`}>{item.imageUrl?<img src={item.imageUrl} alt={item.name}/>:<PackageOpen className="placeholder" size={90} strokeWidth={1.2}/>}<span className={`badge ${item.type.toLowerCase()}`}>{item.type}</span>{item.isResolved&&<span className="badge resolved">Resolved</span>}</div><div className="detail-content"><h1>{item.name}</h1><div className="meta"><span><MapPin size={14}/>{item.location}</span><span><CalendarDays size={14}/>{formatDate(item.date)}</span></div><p className="detail-description">{item.description}</p></div></article><aside className="side-card"><h3>Report information</h3><dl className="info-list"><div className="info-row"><span className="info-icon"><MapPin size={17}/></span><div><dt>Location</dt><dd>{item.location}</dd></div></div><div className="info-row"><span className="info-icon"><CalendarDays size={17}/></span><div><dt>Date {item.type.toLowerCase()}</dt><dd>{formatDate(item.date)}</dd></div></div><div className="info-row"><span className="info-icon"><Mail size={17}/></span><div><dt>Contact</dt><dd>{item.contactInfo}</dd></div></div><div className="info-row"><span className="info-icon"><Clock3 size={17}/></span><div><dt>Reported</dt><dd>{new Intl.DateTimeFormat('en-LK',{dateStyle:'medium'}).format(new Date(item.createdAt))}</dd></div></div></dl><div className="action-stack">{!item.isResolved&&<button className="btn btn-primary" onClick={resolve} disabled={busy}><CheckCircle2 size={17}/> Mark as resolved</button>}<Link className="btn btn-secondary" to={`/items/${item.id}/edit`}><Pencil size={16}/> Edit report</Link><button className="btn btn-danger" onClick={remove} disabled={busy}><Trash2 size={16}/> Delete report</button></div></aside></div></div></section>
}
